# Site settings
baseURL = "https://example.org/"
languageCode = "en-US"
title = "Split - HTML Template Demo"
theme = "hugo-split-fnjoha"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Francis Njoh"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2017 Francis Njoh"

  # Section - Content
  [params.content]
    name = "Francis Njoh"
    tagline = "Cloud Architect. Designer. Maker."
    bio = "I am a passion Cloud Engineer by day and curiouser and curiouser Cloud Architect by night. I believe simplicity is key to productive outcome and habitual learning is key to growth. I strongly believe in applying my Cloud Computing knowledge to help maintain the integrity of the customer facing brands. Feel free to click on the links below if you want to know more"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/IMG_0052.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "#"

      [[params.links.list1.link]]
        text = "Resume"
        url = "https://www.linkedin.com/in/francis-njoh/details/experience/"

      [[params.links.list1.link]]
        text = "Linkedin"
        url = "https://www.linkedin.com/in/francis-njoh"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/fnjoha1"

      [[params.links.list2.link]]
        text = "Youtube"
        url = "#"

      [[params.links.list2.link]]
        text = "Github"
        url = "https://github.com/fnjoha"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Projects"

      [[params.links.list3.link]]
        text = "Link One"
        url = "https://github.com/fnjoha/hugo-sustain"

      [[params.links.list3.link]]
        text = "Link Two"
        url = "https://github.com/fnjoha/Homemade-radiation-hugo2"

      [[params.links.list3.link]]
        text = "Link Three"
        url = "https://github.com/fnjoha/portio-hugo"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
